---
- hosts: localhost
  connection: local

  tasks:
  - name: Create bucket
    amazon.aws.s3_bucket:
      name: "{{ bucket_name }}" 
      state: present

  - name: Create an user called {{ user_name }}
    community.aws.iam_user:
      name: "{{ user_name }}"
      state: present 
    register: new_user

  - name: Create a new access key for {{ user_name }}
    community.aws.iam_access_key:
      user_name: "{{ user_name }}"
      state: present
    no_log: true
    register: new_access_key

  - name: Apply Policies 
    amazon.aws.s3_bucket:
      name: "{{ bucket_name }}" 
      policy: "{{ lookup('template','templates/policy.json.j2') }}" 
    register: policy_result
    retries: 10
    until: "policy_result is not failed"
    delay: 10

  - name: Create a file with S3 credentials
    template:
      src: templates/s3_credentials.j2
      dest: s3_credentials.txt

  - name: Final info
    debug:
      msg: "Credentials stored in s3_credentials.txt" 
